package com.apache.fastandroid

data class SupplierDetailInfo(
    val check_user_id: String,
    val check_user_name: String,
    val checked_supplier_id: String,
    val checked_supplier_name: String,
    val checked_user_id: String,
    val checked_user_name: String,
    val code: String,
    val contract: String,
    val contract_name: String,
    val create_time: String,
    val deadline_time: String,
    val divide_id: String,
    val divide_name: String,
    val form_data_rev_: Int,
    val handle_status: String,
    val handle_status_name: String,
    val id_: String,
    val initData: InitData,
    val line: String,
    val line_name: String,
    val proc_inst_id_: String,
    val row_time: String,
    val row_version: String,
    val status: String,
    val supplier_user_ids: String,
    val unqualified_describe: String,
    val unqualified_level: String,
    val unqualified_level_name: String
)